services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    platform: linux/x86_64
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./docker/nginx/logs/nginx:/var/log/nginx
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: nextjs-client
    platform: linux/x86_64
    tty: true
    expose:
      - "3000"
    volumes:
      - ./frontend:/app/frontend

  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: nestjs-server
    platform: linux/x86_64
    tty: true
    expose:
      - "3000"
    depends_on:
      - database
    volumes:
      - ./backend:/app/backend

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    container_name: postgres-db
    platform: linux/x86_64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/database/postgres/data:/var/lib/postgresql/data
    expose:
      - "5432"
