version: "3.8"

services:
  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://johndoe:password@db:5432/postgres?schema=public"
      # DATABASE_URL: "postgresql://postgres:Ratio0903@db:5432/postgres?schema=public"
    networks:
      - nestjs-network

  db:
    image: postgres:15
    container_name: nestjs-db
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nestjs-network

volumes:
  postgres-data:

networks:
  nestjs-network:
    driver: bridge